# required line: specify the version of the docker-compose 
version: '3'

# services usually = container
services: 
  # name of the service/container
  # by specifying all the services needed in the file, docker compose will automatically build the netrowk connection among them
  web: 
    # specify the umage to be used to create the container
    # build: will not be able to detect dockerfile.dev
    build: 
      # context option: specify where we want all the files and folders
      # if we have nested folder: context: child_folder
      # dockerfile -> specify the docker file to use to construct the image
      context: .
      dockerfile: Dockerfile.dev
    ports:
    # dash is how to specify an array in yml file, so many different ports could be mapped
    # local machine port:container port
      - "3000:3000"
    volumes:
      - /app/node_modules
      # map between local folder to folder in the container
      - .:/app
  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    # overwrite the primary command
    command: ["npm", "run", "test"]
